# Generated by Django 5.2 on 2025-05-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tileset',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='tileset',
            name='image',
            field=models.ImageField(default='aaa', upload_to='tilesets/'),
            preserve_default=False,
        ),
    ]
