# Generated by Django 5.2 on 2025-05-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_tileset_imageurl_tileset_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tileset',
            name='tile_size',
            field=models.CharField(default='8', max_length=255),
            preserve_default=False,
        ),
    ]
