/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TilebuilderImport } from './routes/tilebuilder'
import { Route as GeneratorImport } from './routes/generator'
import { Route as RegisterImport } from './routes/Register'
import { Route as LoginImport } from './routes/Login'
import { Route as IndexImport } from './routes/index'
import { Route as TilesocketListImport } from './routes/tilesocket/list'
import { Route as TilesocketCreateImport } from './routes/tilesocket/create'
import { Route as TilesetListImport } from './routes/tileset/list'
import { Route as TilesetCreateImport } from './routes/tileset/create'
import { Route as TilegroupListImport } from './routes/tilegroup/list'
import { Route as TilegroupCreateImport } from './routes/tilegroup/create'
import { Route as TileListImport } from './routes/tile/list'
import { Route as TileCreateImport } from './routes/tile/create'
import { Route as TilesocketDetailIdImport } from './routes/tilesocket/detail.$id'
import { Route as TilesetDetailIdImport } from './routes/tileset/detail.$id'
import { Route as TilegroupDetailIdImport } from './routes/tilegroup/detail.$id'
import { Route as TileDetailIdImport } from './routes/tile/detail.$id'

// Create/Update Routes

const TilebuilderRoute = TilebuilderImport.update({
  id: '/tilebuilder',
  path: '/tilebuilder',
  getParentRoute: () => rootRoute,
} as any)

const GeneratorRoute = GeneratorImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  id: '/Register',
  path: '/Register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/Login',
  path: '/Login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TilesocketListRoute = TilesocketListImport.update({
  id: '/tilesocket/list',
  path: '/tilesocket/list',
  getParentRoute: () => rootRoute,
} as any)

const TilesocketCreateRoute = TilesocketCreateImport.update({
  id: '/tilesocket/create',
  path: '/tilesocket/create',
  getParentRoute: () => rootRoute,
} as any)

const TilesetListRoute = TilesetListImport.update({
  id: '/tileset/list',
  path: '/tileset/list',
  getParentRoute: () => rootRoute,
} as any)

const TilesetCreateRoute = TilesetCreateImport.update({
  id: '/tileset/create',
  path: '/tileset/create',
  getParentRoute: () => rootRoute,
} as any)

const TilegroupListRoute = TilegroupListImport.update({
  id: '/tilegroup/list',
  path: '/tilegroup/list',
  getParentRoute: () => rootRoute,
} as any)

const TilegroupCreateRoute = TilegroupCreateImport.update({
  id: '/tilegroup/create',
  path: '/tilegroup/create',
  getParentRoute: () => rootRoute,
} as any)

const TileListRoute = TileListImport.update({
  id: '/tile/list',
  path: '/tile/list',
  getParentRoute: () => rootRoute,
} as any)

const TileCreateRoute = TileCreateImport.update({
  id: '/tile/create',
  path: '/tile/create',
  getParentRoute: () => rootRoute,
} as any)

const TilesocketDetailIdRoute = TilesocketDetailIdImport.update({
  id: '/tilesocket/detail/$id',
  path: '/tilesocket/detail/$id',
  getParentRoute: () => rootRoute,
} as any)

const TilesetDetailIdRoute = TilesetDetailIdImport.update({
  id: '/tileset/detail/$id',
  path: '/tileset/detail/$id',
  getParentRoute: () => rootRoute,
} as any)

const TilegroupDetailIdRoute = TilegroupDetailIdImport.update({
  id: '/tilegroup/detail/$id',
  path: '/tilegroup/detail/$id',
  getParentRoute: () => rootRoute,
} as any)

const TileDetailIdRoute = TileDetailIdImport.update({
  id: '/tile/detail/$id',
  path: '/tile/detail/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Login': {
      id: '/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/Register': {
      id: '/Register'
      path: '/Register'
      fullPath: '/Register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/generator': {
      id: '/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof GeneratorImport
      parentRoute: typeof rootRoute
    }
    '/tilebuilder': {
      id: '/tilebuilder'
      path: '/tilebuilder'
      fullPath: '/tilebuilder'
      preLoaderRoute: typeof TilebuilderImport
      parentRoute: typeof rootRoute
    }
    '/tile/create': {
      id: '/tile/create'
      path: '/tile/create'
      fullPath: '/tile/create'
      preLoaderRoute: typeof TileCreateImport
      parentRoute: typeof rootRoute
    }
    '/tile/list': {
      id: '/tile/list'
      path: '/tile/list'
      fullPath: '/tile/list'
      preLoaderRoute: typeof TileListImport
      parentRoute: typeof rootRoute
    }
    '/tilegroup/create': {
      id: '/tilegroup/create'
      path: '/tilegroup/create'
      fullPath: '/tilegroup/create'
      preLoaderRoute: typeof TilegroupCreateImport
      parentRoute: typeof rootRoute
    }
    '/tilegroup/list': {
      id: '/tilegroup/list'
      path: '/tilegroup/list'
      fullPath: '/tilegroup/list'
      preLoaderRoute: typeof TilegroupListImport
      parentRoute: typeof rootRoute
    }
    '/tileset/create': {
      id: '/tileset/create'
      path: '/tileset/create'
      fullPath: '/tileset/create'
      preLoaderRoute: typeof TilesetCreateImport
      parentRoute: typeof rootRoute
    }
    '/tileset/list': {
      id: '/tileset/list'
      path: '/tileset/list'
      fullPath: '/tileset/list'
      preLoaderRoute: typeof TilesetListImport
      parentRoute: typeof rootRoute
    }
    '/tilesocket/create': {
      id: '/tilesocket/create'
      path: '/tilesocket/create'
      fullPath: '/tilesocket/create'
      preLoaderRoute: typeof TilesocketCreateImport
      parentRoute: typeof rootRoute
    }
    '/tilesocket/list': {
      id: '/tilesocket/list'
      path: '/tilesocket/list'
      fullPath: '/tilesocket/list'
      preLoaderRoute: typeof TilesocketListImport
      parentRoute: typeof rootRoute
    }
    '/tile/detail/$id': {
      id: '/tile/detail/$id'
      path: '/tile/detail/$id'
      fullPath: '/tile/detail/$id'
      preLoaderRoute: typeof TileDetailIdImport
      parentRoute: typeof rootRoute
    }
    '/tilegroup/detail/$id': {
      id: '/tilegroup/detail/$id'
      path: '/tilegroup/detail/$id'
      fullPath: '/tilegroup/detail/$id'
      preLoaderRoute: typeof TilegroupDetailIdImport
      parentRoute: typeof rootRoute
    }
    '/tileset/detail/$id': {
      id: '/tileset/detail/$id'
      path: '/tileset/detail/$id'
      fullPath: '/tileset/detail/$id'
      preLoaderRoute: typeof TilesetDetailIdImport
      parentRoute: typeof rootRoute
    }
    '/tilesocket/detail/$id': {
      id: '/tilesocket/detail/$id'
      path: '/tilesocket/detail/$id'
      fullPath: '/tilesocket/detail/$id'
      preLoaderRoute: typeof TilesocketDetailIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Login': typeof LoginRoute
  '/Register': typeof RegisterRoute
  '/generator': typeof GeneratorRoute
  '/tilebuilder': typeof TilebuilderRoute
  '/tile/create': typeof TileCreateRoute
  '/tile/list': typeof TileListRoute
  '/tilegroup/create': typeof TilegroupCreateRoute
  '/tilegroup/list': typeof TilegroupListRoute
  '/tileset/create': typeof TilesetCreateRoute
  '/tileset/list': typeof TilesetListRoute
  '/tilesocket/create': typeof TilesocketCreateRoute
  '/tilesocket/list': typeof TilesocketListRoute
  '/tile/detail/$id': typeof TileDetailIdRoute
  '/tilegroup/detail/$id': typeof TilegroupDetailIdRoute
  '/tileset/detail/$id': typeof TilesetDetailIdRoute
  '/tilesocket/detail/$id': typeof TilesocketDetailIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Login': typeof LoginRoute
  '/Register': typeof RegisterRoute
  '/generator': typeof GeneratorRoute
  '/tilebuilder': typeof TilebuilderRoute
  '/tile/create': typeof TileCreateRoute
  '/tile/list': typeof TileListRoute
  '/tilegroup/create': typeof TilegroupCreateRoute
  '/tilegroup/list': typeof TilegroupListRoute
  '/tileset/create': typeof TilesetCreateRoute
  '/tileset/list': typeof TilesetListRoute
  '/tilesocket/create': typeof TilesocketCreateRoute
  '/tilesocket/list': typeof TilesocketListRoute
  '/tile/detail/$id': typeof TileDetailIdRoute
  '/tilegroup/detail/$id': typeof TilegroupDetailIdRoute
  '/tileset/detail/$id': typeof TilesetDetailIdRoute
  '/tilesocket/detail/$id': typeof TilesocketDetailIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/Login': typeof LoginRoute
  '/Register': typeof RegisterRoute
  '/generator': typeof GeneratorRoute
  '/tilebuilder': typeof TilebuilderRoute
  '/tile/create': typeof TileCreateRoute
  '/tile/list': typeof TileListRoute
  '/tilegroup/create': typeof TilegroupCreateRoute
  '/tilegroup/list': typeof TilegroupListRoute
  '/tileset/create': typeof TilesetCreateRoute
  '/tileset/list': typeof TilesetListRoute
  '/tilesocket/create': typeof TilesocketCreateRoute
  '/tilesocket/list': typeof TilesocketListRoute
  '/tile/detail/$id': typeof TileDetailIdRoute
  '/tilegroup/detail/$id': typeof TilegroupDetailIdRoute
  '/tileset/detail/$id': typeof TilesetDetailIdRoute
  '/tilesocket/detail/$id': typeof TilesocketDetailIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Login'
    | '/Register'
    | '/generator'
    | '/tilebuilder'
    | '/tile/create'
    | '/tile/list'
    | '/tilegroup/create'
    | '/tilegroup/list'
    | '/tileset/create'
    | '/tileset/list'
    | '/tilesocket/create'
    | '/tilesocket/list'
    | '/tile/detail/$id'
    | '/tilegroup/detail/$id'
    | '/tileset/detail/$id'
    | '/tilesocket/detail/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Login'
    | '/Register'
    | '/generator'
    | '/tilebuilder'
    | '/tile/create'
    | '/tile/list'
    | '/tilegroup/create'
    | '/tilegroup/list'
    | '/tileset/create'
    | '/tileset/list'
    | '/tilesocket/create'
    | '/tilesocket/list'
    | '/tile/detail/$id'
    | '/tilegroup/detail/$id'
    | '/tileset/detail/$id'
    | '/tilesocket/detail/$id'
  id:
    | '__root__'
    | '/'
    | '/Login'
    | '/Register'
    | '/generator'
    | '/tilebuilder'
    | '/tile/create'
    | '/tile/list'
    | '/tilegroup/create'
    | '/tilegroup/list'
    | '/tileset/create'
    | '/tileset/list'
    | '/tilesocket/create'
    | '/tilesocket/list'
    | '/tile/detail/$id'
    | '/tilegroup/detail/$id'
    | '/tileset/detail/$id'
    | '/tilesocket/detail/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  GeneratorRoute: typeof GeneratorRoute
  TilebuilderRoute: typeof TilebuilderRoute
  TileCreateRoute: typeof TileCreateRoute
  TileListRoute: typeof TileListRoute
  TilegroupCreateRoute: typeof TilegroupCreateRoute
  TilegroupListRoute: typeof TilegroupListRoute
  TilesetCreateRoute: typeof TilesetCreateRoute
  TilesetListRoute: typeof TilesetListRoute
  TilesocketCreateRoute: typeof TilesocketCreateRoute
  TilesocketListRoute: typeof TilesocketListRoute
  TileDetailIdRoute: typeof TileDetailIdRoute
  TilegroupDetailIdRoute: typeof TilegroupDetailIdRoute
  TilesetDetailIdRoute: typeof TilesetDetailIdRoute
  TilesocketDetailIdRoute: typeof TilesocketDetailIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  GeneratorRoute: GeneratorRoute,
  TilebuilderRoute: TilebuilderRoute,
  TileCreateRoute: TileCreateRoute,
  TileListRoute: TileListRoute,
  TilegroupCreateRoute: TilegroupCreateRoute,
  TilegroupListRoute: TilegroupListRoute,
  TilesetCreateRoute: TilesetCreateRoute,
  TilesetListRoute: TilesetListRoute,
  TilesocketCreateRoute: TilesocketCreateRoute,
  TilesocketListRoute: TilesocketListRoute,
  TileDetailIdRoute: TileDetailIdRoute,
  TilegroupDetailIdRoute: TilegroupDetailIdRoute,
  TilesetDetailIdRoute: TilesetDetailIdRoute,
  TilesocketDetailIdRoute: TilesocketDetailIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Login",
        "/Register",
        "/generator",
        "/tilebuilder",
        "/tile/create",
        "/tile/list",
        "/tilegroup/create",
        "/tilegroup/list",
        "/tileset/create",
        "/tileset/list",
        "/tilesocket/create",
        "/tilesocket/list",
        "/tile/detail/$id",
        "/tilegroup/detail/$id",
        "/tileset/detail/$id",
        "/tilesocket/detail/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/Login": {
      "filePath": "Login.jsx"
    },
    "/Register": {
      "filePath": "Register.jsx"
    },
    "/generator": {
      "filePath": "generator.tsx"
    },
    "/tilebuilder": {
      "filePath": "tilebuilder.tsx"
    },
    "/tile/create": {
      "filePath": "tile/create.tsx"
    },
    "/tile/list": {
      "filePath": "tile/list.tsx"
    },
    "/tilegroup/create": {
      "filePath": "tilegroup/create.tsx"
    },
    "/tilegroup/list": {
      "filePath": "tilegroup/list.tsx"
    },
    "/tileset/create": {
      "filePath": "tileset/create.tsx"
    },
    "/tileset/list": {
      "filePath": "tileset/list.tsx"
    },
    "/tilesocket/create": {
      "filePath": "tilesocket/create.tsx"
    },
    "/tilesocket/list": {
      "filePath": "tilesocket/list.tsx"
    },
    "/tile/detail/$id": {
      "filePath": "tile/detail.$id.tsx"
    },
    "/tilegroup/detail/$id": {
      "filePath": "tilegroup/detail.$id.tsx"
    },
    "/tileset/detail/$id": {
      "filePath": "tileset/detail.$id.tsx"
    },
    "/tilesocket/detail/$id": {
      "filePath": "tilesocket/detail.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
