/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TilebuilderImport } from './routes/tilebuilder'
import { Route as GeneratorImport } from './routes/generator'
import { Route as RegisterImport } from './routes/Register'
import { Route as LoginImport } from './routes/Login'
import { Route as TilesetCreateImport } from './routes/tileset/create'

// Create/Update Routes

const TilebuilderRoute = TilebuilderImport.update({
  id: '/tilebuilder',
  path: '/tilebuilder',
  getParentRoute: () => rootRoute,
} as any)

const GeneratorRoute = GeneratorImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  id: '/Register',
  path: '/Register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/Login',
  path: '/Login',
  getParentRoute: () => rootRoute,
} as any)

const TilesetCreateRoute = TilesetCreateImport.update({
  id: '/tileset/create',
  path: '/tileset/create',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Login': {
      id: '/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/Register': {
      id: '/Register'
      path: '/Register'
      fullPath: '/Register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/generator': {
      id: '/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof GeneratorImport
      parentRoute: typeof rootRoute
    }
    '/tilebuilder': {
      id: '/tilebuilder'
      path: '/tilebuilder'
      fullPath: '/tilebuilder'
      preLoaderRoute: typeof TilebuilderImport
      parentRoute: typeof rootRoute
    }
    '/tileset/create': {
      id: '/tileset/create'
      path: '/tileset/create'
      fullPath: '/tileset/create'
      preLoaderRoute: typeof TilesetCreateImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/Login': typeof LoginRoute
  '/Register': typeof RegisterRoute
  '/generator': typeof GeneratorRoute
  '/tilebuilder': typeof TilebuilderRoute
  '/tileset/create': typeof TilesetCreateRoute
}

export interface FileRoutesByTo {
  '/Login': typeof LoginRoute
  '/Register': typeof RegisterRoute
  '/generator': typeof GeneratorRoute
  '/tilebuilder': typeof TilebuilderRoute
  '/tileset/create': typeof TilesetCreateRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/Login': typeof LoginRoute
  '/Register': typeof RegisterRoute
  '/generator': typeof GeneratorRoute
  '/tilebuilder': typeof TilebuilderRoute
  '/tileset/create': typeof TilesetCreateRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/Login'
    | '/Register'
    | '/generator'
    | '/tilebuilder'
    | '/tileset/create'
  fileRoutesByTo: FileRoutesByTo
  to: '/Login' | '/Register' | '/generator' | '/tilebuilder' | '/tileset/create'
  id:
    | '__root__'
    | '/Login'
    | '/Register'
    | '/generator'
    | '/tilebuilder'
    | '/tileset/create'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  GeneratorRoute: typeof GeneratorRoute
  TilebuilderRoute: typeof TilebuilderRoute
  TilesetCreateRoute: typeof TilesetCreateRoute
}

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  GeneratorRoute: GeneratorRoute,
  TilebuilderRoute: TilebuilderRoute,
  TilesetCreateRoute: TilesetCreateRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/Login",
        "/Register",
        "/generator",
        "/tilebuilder",
        "/tileset/create"
      ]
    },
    "/Login": {
      "filePath": "Login.jsx"
    },
    "/Register": {
      "filePath": "Register.jsx"
    },
    "/generator": {
      "filePath": "generator.tsx"
    },
    "/tilebuilder": {
      "filePath": "tilebuilder.tsx"
    },
    "/tileset/create": {
      "filePath": "tileset/create.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
