/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TilebuilderImport } from './routes/tilebuilder'
import { Route as GeneratorImport } from './routes/generator'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TilebuilderRoute = TilebuilderImport.update({
  id: '/tilebuilder',
  path: '/tilebuilder',
  getParentRoute: () => rootRoute,
} as any)

const GeneratorRoute = GeneratorImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/generator': {
      id: '/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof GeneratorImport
      parentRoute: typeof rootRoute
    }
    '/tilebuilder': {
      id: '/tilebuilder'
      path: '/tilebuilder'
      fullPath: '/tilebuilder'
      preLoaderRoute: typeof TilebuilderImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/generator': typeof GeneratorRoute
  '/tilebuilder': typeof TilebuilderRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generator': typeof GeneratorRoute
  '/tilebuilder': typeof TilebuilderRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/generator': typeof GeneratorRoute
  '/tilebuilder': typeof TilebuilderRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/generator' | '/tilebuilder'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/generator' | '/tilebuilder'
  id: '__root__' | '/' | '/generator' | '/tilebuilder'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GeneratorRoute: typeof GeneratorRoute
  TilebuilderRoute: typeof TilebuilderRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GeneratorRoute: GeneratorRoute,
  TilebuilderRoute: TilebuilderRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/generator",
        "/tilebuilder"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/generator": {
      "filePath": "generator.tsx"
    },
    "/tilebuilder": {
      "filePath": "tilebuilder.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
